language: generic

jobs:
  include:
    - stage: Test
      name: Linux SwiftPM 4.0
      os: linux
      dist: trusty
      sudo: required
      install:
      - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      - swiftenv install 4.0
      - swiftenv local 4.0
      - swift --version
      script:
      - swift test
      - swift test --parallel
    - stage: Test
      name: macOS SwiftPM
      os: osx
      osx_image: xcode9.3
      script:
      - swift test
      - swift test --parallel
    - stage: Test
      name: macOS Xcode 9.3 (Code Coverage)
      os: osx
      osx_image: xcode9.3
      script:
      - swift package generate-xcodeproj --enable-code-coverage
      - xcodebuild -scheme OrderedDictionary-Package test
      after_success:
      - bash <(curl -s https://codecov.io/bash);

